export default {
    'nav.employees': 'Employees',
    'nav.addNew': 'Add New',
    'nav.language': 'Language',
    'employeeList.title': 'Employee List',
    'employeeList.search': 'Search employees...',
    'employeeForm.cancel': 'Cancel',
    'employeeList.toggleView': 'Switch to',
    'employeeList.firstName': 'First Name',
    'employeeList.lastName': 'Last Name',
    'employeeList.dateOfEmployment': 'Date of Employment',
    'employeeList.dateOfBirth': 'Date of Birth',
    'employeeList.phone': 'Phone',
    'employeeList.email': 'Email',
    'employeeList.department': 'Department',
    'employeeList.position': 'Position',
    'employeeList.actions': 'Actions',
    'employeeList.edit': 'Edit',
    'employeeList.delete': 'Delete',
    'employeeForm.addTitle': 'Add New Employee',
    'employeeForm.editTitle': 'Edit Employee',
    'employeeForm.firstName': 'First Name',
    'employeeForm.lastName': 'Last Name',
    'employeeForm.dateOfEmployment': 'Date of Employment',
    'employeeForm.dateOfBirth': 'Date of Birth',
    'employeeForm.phone': 'Phone',
    'employeeForm.email': 'Email',
    'employeeForm.department': 'Department',
    'employeeForm.position': 'Position',
    'employeeForm.add': 'Add Employee',
    'employeeForm.update': 'Update Employee',
    'deleteConfirmation.message': 'Selected employee record of {name} will be deleted.',
    'deleteConfirmation.proceed': 'Proceed',
    'deleteConfirmation.cancel': 'Cancel',
    'updateConfirmation.message': 'Are you sure you want to update this employee?',
    'updateConfirmation.proceed': 'Update',
    'updateConfirmation.cancel': 'Cancel',
    'errors.firstNameRequired': 'First name is required',
    'errors.lastNameRequired': 'Last name is required',
    'errors.dateOfEmploymentRequired': 'Date of employment is required',
    'errors.dateOfBirthRequired': 'Date of birth is required',
    'errors.phoneInvalid': 'Invalid phone number. Must be with + country code (+90*******)',
    'errors.emailInvalid': 'Invalid email format',
    'errors.emailTaken': 'Email already exists',
};