export default {
    'nav.employees': 'Çalışanlar',
    'nav.addNew': 'Yeni Ekle',
    'nav.language': 'Dil',
    'employeeList.title': 'Çalışan Listesi',
    'employeeList.search': 'Çalışan ara...',
    'employeeList.toggleView': 'Şuna geç:',
    'employeeList.firstName': 'Ad',
    'employeeList.lastName': 'Soyad',
    'employeeForm.cancel': 'İptal Et',
    'employeeList.dateOfEmployment': 'İşe Başlama Tarihi',
    'employeeList.dateOfBirth': 'Doğum Tarihi',
    'employeeList.phone': 'Telefon',
    'employeeList.email': 'E-posta',
    'employeeList.department': 'Departman',
    'employeeList.position': 'Pozisyon',
    'employeeList.actions': 'Eylemler',
    'employeeList.edit': 'Düzenle',
    'employeeList.delete': 'Sil',
    'employeeForm.addTitle': 'Yeni Çalışan Ekle',
    'employeeForm.editTitle': 'Çalışanı Düzenle',
    'employeeForm.firstName': 'Ad',
    'employeeForm.lastName': 'Soyad',
    'employeeForm.dateOfEmployment': 'İşe Başlama Tarihi',
    'employeeForm.dateOfBirth': 'Doğum Tarihi',
    'employeeForm.phone': 'Telefon',
    'employeeForm.email': 'E-posta',
    'employeeForm.department': 'Departman',
    'employeeForm.position': 'Pozisyon',
    'employeeForm.add': 'Çalışan Ekle',
    'employeeForm.update': 'Çalışanı Güncelle',
    'deleteConfirmation.message': '{name} adlı çalışanın kaydı silinecek, emin misiniz?',
    'deleteConfirmation.proceed': 'İlerle',
    'deleteConfirmation.cancel': 'İptal',
    'updateConfirmation.message': 'Bu çalışanı güncellemek istediğinizden emin misiniz?',
    'updateConfirmation.proceed': 'Güncelle',
    'updateConfirmation.cancel': 'İptal',
    'errors.firstNameRequired': 'Ad gerekli',
    'errors.lastNameRequired': 'Soyad gerekli',
    'errors.dateOfEmploymentRequired': 'İşe başlama tarihi gerekli',
    'errors.dateOfBirthRequired': 'Doğum tarihi gerekli',
    'errors.phoneInvalid': 'Geçersiz telefon numarası ülke kodu ile birlikte olmalı (+90*******)',
    'errors.emailInvalid': 'Geçersiz e-posta formatı',
    'errors.emailTaken': 'E-posta zaten mevcut',
};